<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            // Web Development Courses
            [
                'course_name' => 'Complete Web Development Bootcamp',
                'description' => 'Learn HTML, CSS, JavaScript, Node.js, React, and more in this comprehensive bootcamp.',
                'url' => 'https://www.udemy.com/course/the-complete-web-development-bootcamp/',
                'provider' => 'Udemy',
                'duration_hours' => 54.5,
                'is_free' => false,
                'cost' => 84.99,
                'category' => 'Web Development',
                'related_skills' => ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
                'career_paths' => ['Full Stack Developer', 'Frontend Developer', 'Backend Developer'],
                'instructor' => 'Angela Yu',
                'difficulty_level' => 1.0,
                'is_active' => true,
            ],
            [
                'course_name' => 'JavaScript Algorithms and Data Structures',
                'description' => 'Master algorithms and data structures in JavaScript with over 300 hours of content.',
                'url' => 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/',
                'provider' => 'freeCodeCamp',
                'duration_hours' => 300.0,
                'is_free' => true,
                'cost' => null,
                'category' => 'Web Development',
                'related_skills' => ['JavaScript', 'Algorithms', 'Data Structures', 'Problem Solving'],
                'career_paths' => ['Software Engineer', 'Full Stack Developer'],
                'instructor' => 'freeCodeCamp Team',
                'difficulty_level' => 2.0,
                'is_active' => true,
            ],
            [
                'course_name' => 'React - The Complete Guide',
                'description' => 'Dive deep into React.js with hooks, Redux, routing, and Next.js.',
                'url' => 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/',
                'provider' => 'Udemy',
                'duration_hours' => 48.0,
                'is_free' => false,
                'cost' => 89.99,
                'category' => 'Web Development',
                'related_skills' => ['React', 'Redux', 'Next.js', 'JavaScript'],
                'career_paths' => ['Frontend Developer', 'React Developer'],
                'instructor' => 'Maximilian Schwarzmüller',
                'difficulty_level' => 2.0,
                'is_active' => true,
            ],
            [
                'course_name' => 'Node.js, Express, MongoDB & More',
                'description' => 'Build fast, scalable REST APIs with Node.js, Express, and MongoDB.',
                'url' => 'https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/',
                'provider' => 'Udemy',
                'duration_hours' => 42.0,
                'is_free' => false,
                'cost' => 79.99,
                'category' => 'Web Development',
                'related_skills' => ['Node.js', 'Express', 'MongoDB', 'REST API'],
                'career_paths' => ['Backend Developer', 'Full Stack Developer'],
                'instructor' => 'Jonas Schmedtmann',
                'difficulty_level' => 2.5,
                'is_active' => true,
            ],
            [
                'course_name' => 'HTML & CSS for Beginners',
                'description' => 'Learn the fundamentals of HTML and CSS from scratch.',
                'url' => 'https://www.youtube.com/watch?v=hu-q2zYwEYs',
                'provider' => 'YouTube',
                'duration_hours' => 4.0,
                'is_free' => true,
                'cost' => null,
                'category' => 'Web Development',
                'related_skills' => ['HTML', 'CSS', 'Web Design'],
                'career_paths' => ['Web Designer', 'Frontend Developer'],
                'instructor' => 'Dave Gray',
                'difficulty_level' => 1.0,
                'is_active' => true,
            ],

            // Data Science & AI
            [
                'course_name' => 'Machine Learning Specialization',
                'description' => 'Master fundamental machine learning concepts from Andrew Ng.',
                'url' => 'https://www.coursera.org/specializations/machine-learning-introduction',
                'provider' => 'Coursera',
                'duration_hours' => 80.0,
                'is_free' => false,
                'cost' => 49.00,
                'category' => 'Data Science',
                'related_skills' => ['Machine Learning', 'Python', 'Neural Networks', 'TensorFlow'],
                'career_paths' => ['ML Engineer', 'Data Scientist', 'AI Researcher'],
                'instructor' => 'Andrew Ng',
                'difficulty_level' => 2.5,
                'is_active' => true,
            ],
            [
                'course_name' => 'Python for Data Science and Machine Learning',
                'description' => 'Learn Python, NumPy, Pandas, Matplotlib, Seaborn, Scikit-Learn, and more.',
                'url' => 'https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/',
                'provider' => 'Udemy',
                'duration_hours' => 25.0,
                'is_free' => false,
                'cost' => 74.99,
                'category' => 'Data Science',
                'related_skills' => ['Python', 'Pandas', 'Machine Learning', 'Data Analysis'],
                'career_paths' => ['Data Scientist', 'Data Analyst'],
                'instructor' => 'Jose Portilla',
                'difficulty_level' => 2.0,
                'is_active' => true,
            ],
            [
                'course_name' => 'Deep Learning Specialization',
                'description' => '5-course specialization covering neural networks, CNNs, RNNs, and more.',
                'url' => 'https://www.coursera.org/specializations/deep-learning',
                'provider' => 'Coursera',
                'duration_hours' => 120.0,
                'is_free' => false,
                'cost' => 49.00,
                'category' => 'Data Science',
                'related_skills' => ['Deep Learning', 'Neural Networks', 'TensorFlow', 'Python'],
                'career_paths' => ['AI Engineer', 'ML Engineer', 'Research Scientist'],
                'instructor' => 'Andrew Ng',
                'difficulty_level' => 3.0,
                'is_active' => true,
            ],
            [
                'course_name' => 'Data Analysis with Python',
                'description' => 'Free course on data analysis using Python, Pandas, and Jupyter.',
                'url' => 'https://www.freecodecamp.org/learn/data-analysis-with-python/',
                'provider' => 'freeCodeCamp',
                'duration_hours' => 10.0,
                'is_free' => true,
                'cost' => null,
                'category' => 'Data Science',
                'related_skills' => ['Python', 'Pandas', 'NumPy', 'Matplotlib'],
                'career_paths' => ['Data Analyst', 'Business Analyst'],
                'instructor' => 'freeCodeCamp Team',
                'difficulty_level' => 1.5,
                'is_active' => true,
            ],
            [
                'course_name' => 'SQL for Data Science',
                'description' => 'Master SQL for data analysis and database management.',
                'url' => 'https://www.coursera.org/learn/sql-for-data-science',
                'provider' => 'Coursera',
                'duration_hours' => 15.0,
                'is_free' => true,
                'cost' => null,
                'category' => 'Data Science',
                'related_skills' => ['SQL', 'Database Management', 'Data Analysis'],
                'career_paths' => ['Data Analyst', 'Database Administrator'],
                'instructor' => 'Sadie St. Lawrence',
                'difficulty_level' => 1.5,
                'is_active' => true,
            ],

            // Leadership & Business
            [
                'course_name' => 'Leadership and Management',
                'description' => 'Develop essential leadership skills for managing teams effectively.',
                'url' => 'https://www.linkedin.com/learning/topics/leadership-and-management',
                'provider' => 'LinkedIn Learning',
                'duration_hours' => 12.0,
                'is_free' => false,
                'cost' => 39.99,
                'category' => 'Leadership',
                'related_skills' => ['Leadership', 'Management', 'Team Building', 'Communication'],
                'career_paths' => ['Team Lead', 'Manager', 'Director'],
                'instructor' => 'Chris Croft',
                'difficulty_level' => 2.0,
                'is_active' => true,
            ],
            [
                'course_name' => 'Project Management Professional (PMP)',
                'description' => 'Complete PMP certification training covering all PMI knowledge areas.',
                'url' => 'https://www.udemy.com/course/pmp-certification-exam-prep-seminar-pmbok/',
                'provider' => 'Udemy',
                'duration_hours' => 35.0,
                'is_free' => false,
                'cost' => 94.99,
                'category' => 'Leadership',
                'related_skills' => ['Project Management', 'Agile', 'Risk Management', 'Planning'],
                'career_paths' => ['Project Manager', 'Program Manager'],
                'instructor' => 'Joseph Phillips',
                'difficulty_level' => 2.5,
                'is_active' => true,
            ],
            [
                'course_name' => 'Entrepreneurship 101',
                'description' => 'Learn how to start and grow your own business from successful entrepreneurs.',
                'url' => 'https://www.youtube.com/watch?v=kC-dP70NExY',
                'provider' => 'YouTube',
                'duration_hours' => 8.0,
                'is_free' => true,
                'cost' => null,
                'category' => 'Business',
                'related_skills' => ['Entrepreneurship', 'Business Planning', 'Marketing', 'Finance'],
                'career_paths' => ['Entrepreneur', 'Business Owner', 'Startup Founder'],
                'instructor' => 'Y Combinator',
                'difficulty_level' => 1.5,
                'is_active' => true,
            ],
            [
                'course_name' => 'Agile Scrum Master Certification',
                'description' => 'Become a certified Scrum Master and learn Agile methodologies.',
                'url' => 'https://www.udemy.com/course/scrum-master-certification-preparation/',
                'provider' => 'Udemy',
                'duration_hours' => 16.0,
                'is_free' => false,
                'cost' => 69.99,
                'category' => 'Leadership',
                'related_skills' => ['Agile', 'Scrum', 'Project Management', 'Team Facilitation'],
                'career_paths' => ['Scrum Master', 'Agile Coach', 'Project Manager'],
                'instructor' => 'Paul Ashun',
                'difficulty_level' => 2.0,
                'is_active' => true,
            ],
            [
                'course_name' => 'Digital Marketing Masterclass',
                'description' => 'Learn SEO, social media marketing, email marketing, and more.',
                'url' => 'https://www.udemy.com/course/learn-digital-marketing-course/',
                'provider' => 'Udemy',
                'duration_hours' => 36.0,
                'is_free' => false,
                'cost' => 79.99,
                'category' => 'Business',
                'related_skills' => ['Digital Marketing', 'SEO', 'Social Media', 'Content Marketing'],
                'career_paths' => ['Digital Marketer', 'Marketing Manager', 'SEO Specialist'],
                'instructor' => 'Phil Ebiner',
                'difficulty_level' => 1.5,
                'is_active' => true,
            ],

            // Mobile Development
            [
                'course_name' => 'iOS & Swift - The Complete iOS App Development',
                'description' => 'Learn iOS development with Swift and build professional apps.',
                'url' => 'https://www.udemy.com/course/ios-13-app-development-bootcamp/',
                'provider' => 'Udemy',
                'duration_hours' => 55.0,
                'is_free' => false,
                'cost' => 84.99,
                'category' => 'Mobile Development',
                'related_skills' => ['Swift', 'iOS', 'Xcode', 'UIKit'],
                'career_paths' => ['iOS Developer', 'Mobile App Developer'],
                'instructor' => 'Angela Yu',
                'difficulty_level' => 2.0,
                'is_active' => true,
            ],
            [
                'course_name' => 'Android Development with Kotlin',
                'description' => 'Build Android apps using Kotlin and Android Studio.',
                'url' => 'https://www.udemy.com/course/android-kotlin-developer/',
                'provider' => 'Udemy',
                'duration_hours' => 32.0,
                'is_free' => false,
                'cost' => 74.99,
                'category' => 'Mobile Development',
                'related_skills' => ['Kotlin', 'Android', 'Android Studio', 'Mobile Development'],
                'career_paths' => ['Android Developer', 'Mobile App Developer'],
                'instructor' => 'Denis Panjuta',
                'difficulty_level' => 2.0,
                'is_active' => true,
            ],
            [
                'course_name' => 'React Native - The Practical Guide',
                'description' => 'Build cross-platform mobile apps with React Native.',
                'url' => 'https://www.udemy.com/course/react-native-the-practical-guide/',
                'provider' => 'Udemy',
                'duration_hours' => 31.5,
                'is_free' => false,
                'cost' => 89.99,
                'category' => 'Mobile Development',
                'related_skills' => ['React Native', 'JavaScript', 'Mobile Development', 'React'],
                'career_paths' => ['Mobile Developer', 'React Native Developer'],
                'instructor' => 'Maximilian Schwarzmüller',
                'difficulty_level' => 2.5,
                'is_active' => true,
            ],
            [
                'course_name' => 'Flutter & Dart - The Complete Guide',
                'description' => 'Build native mobile apps with a single codebase using Flutter.',
                'url' => 'https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/',
                'provider' => 'Udemy',
                'duration_hours' => 42.0,
                'is_free' => false,
                'cost' => 84.99,
                'category' => 'Mobile Development',
                'related_skills' => ['Flutter', 'Dart', 'Mobile Development', 'UI Design'],
                'career_paths' => ['Flutter Developer', 'Mobile App Developer'],
                'instructor' => 'Maximilian Schwarzmüller',
                'difficulty_level' => 2.0,
                'is_active' => true,
            ],

            // Cloud & DevOps
            [
                'course_name' => 'AWS Certified Solutions Architect',
                'description' => 'Prepare for the AWS Solutions Architect certification exam.',
                'url' => 'https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/',
                'provider' => 'Udemy',
                'duration_hours' => 27.0,
                'is_free' => false,
                'cost' => 79.99,
                'category' => 'Cloud Computing',
                'related_skills' => ['AWS', 'Cloud Architecture', 'DevOps', 'Infrastructure'],
                'career_paths' => ['Cloud Architect', 'DevOps Engineer', 'Solutions Architect'],
                'instructor' => 'Stephane Maarek',
                'difficulty_level' => 2.5,
                'is_active' => true,
            ],
            [
                'course_name' => 'Docker and Kubernetes: The Complete Guide',
                'description' => 'Master containerization with Docker and orchestration with Kubernetes.',
                'url' => 'https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/',
                'provider' => 'Udemy',
                'duration_hours' => 22.0,
                'is_free' => false,
                'cost' => 74.99,
                'category' => 'DevOps',
                'related_skills' => ['Docker', 'Kubernetes', 'DevOps', 'Containers'],
                'career_paths' => ['DevOps Engineer', 'Site Reliability Engineer'],
                'instructor' => 'Stephen Grider',
                'difficulty_level' => 2.5,
                'is_active' => true,
            ],
            [
                'course_name' => 'Google Cloud Platform Fundamentals',
                'description' => 'Learn core GCP services and cloud concepts.',
                'url' => 'https://www.coursera.org/learn/gcp-fundamentals',
                'provider' => 'Coursera',
                'duration_hours' => 18.0,
                'is_free' => true,
                'cost' => null,
                'category' => 'Cloud Computing',
                'related_skills' => ['GCP', 'Cloud Computing', 'Infrastructure', 'DevOps'],
                'career_paths' => ['Cloud Engineer', 'DevOps Engineer'],
                'instructor' => 'Google Cloud',
                'difficulty_level' => 1.5,
                'is_active' => true,
            ],
            [
                'course_name' => 'DevOps Bootcamp',
                'description' => 'Complete DevOps training covering CI/CD, automation, and monitoring.',
                'url' => 'https://www.udemy.com/course/devops-bootcamp/',
                'provider' => 'Udemy',
                'duration_hours' => 28.0,
                'is_free' => false,
                'cost' => 79.99,
                'category' => 'DevOps',
                'related_skills' => ['DevOps', 'CI/CD', 'Jenkins', 'Git', 'Docker'],
                'career_paths' => ['DevOps Engineer', 'Site Reliability Engineer'],
                'instructor' => 'Jason Taylor',
                'difficulty_level' => 2.5,
                'is_active' => true,
            ],
        ];

        // Add more courses programmatically to reach 100
        $additionalCourses = [
            // More Web Development
            ['course_name' => 'TypeScript Complete Course', 'category' => 'Web Development', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 8.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Vue.js 3 Masterclass', 'category' => 'Web Development', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 79.99, 'duration_hours' => 28.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Angular - The Complete Guide', 'category' => 'Web Development', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 84.99, 'duration_hours' => 34.0, 'difficulty_level' => 2.5],
            ['course_name' => 'PHP for Beginners', 'category' => 'Web Development', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 5.0, 'difficulty_level' => 1.0],
            ['course_name' => 'Laravel 10 Complete Course', 'category' => 'Web Development', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 74.99, 'duration_hours' => 22.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Django for Everybody', 'category' => 'Web Development', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 40.0, 'difficulty_level' => 2.0],
            ['course_name' => 'GraphQL with React', 'category' => 'Web Development', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 69.99, 'duration_hours' => 18.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Tailwind CSS From Scratch', 'category' => 'Web Development', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 3.0, 'difficulty_level' => 1.0],
            ['course_name' => 'Webpack 5 Complete Guide', 'category' => 'Web Development', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 59.99, 'duration_hours' => 12.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Testing JavaScript with Jest', 'category' => 'Web Development', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 4.0, 'difficulty_level' => 2.0],

            // More Data Science
            ['course_name' => 'R Programming Basics', 'category' => 'Data Science', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 15.0, 'difficulty_level' => 1.5],
            ['course_name' => 'Data Visualization with Tableau', 'category' => 'Data Science', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 74.99, 'duration_hours' => 18.0, 'difficulty_level' => 1.5],
            ['course_name' => 'Statistics for Data Science', 'category' => 'Data Science', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 6.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Big Data with Hadoop', 'category' => 'Data Science', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 79.99, 'duration_hours' => 25.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Natural Language Processing', 'category' => 'Data Science', 'provider' => 'Coursera', 'is_free' => false, 'cost' => 49.00, 'duration_hours' => 45.0, 'difficulty_level' => 3.0],
            ['course_name' => 'Computer Vision A-Z', 'category' => 'Data Science', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 84.99, 'duration_hours' => 38.0, 'difficulty_level' => 3.0],
            ['course_name' => 'Apache Spark Programming', 'category' => 'Data Science', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 74.99, 'duration_hours' => 22.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Data Engineering Fundamentals', 'category' => 'Data Science', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 8.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Power BI Complete Course', 'category' => 'Data Science', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 69.99, 'duration_hours' => 20.0, 'difficulty_level' => 1.5],
            ['course_name' => 'Excel to MySQL', 'category' => 'Data Science', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 12.0, 'difficulty_level' => 1.0],

            // Cybersecurity
            ['course_name' => 'Ethical Hacking Bootcamp', 'category' => 'Cybersecurity', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 94.99, 'duration_hours' => 40.0, 'difficulty_level' => 2.5],
            ['course_name' => 'CompTIA Security+ Certification', 'category' => 'Cybersecurity', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 84.99, 'duration_hours' => 30.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Network Security Essentials', 'category' => 'Cybersecurity', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 18.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Web Application Security', 'category' => 'Cybersecurity', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 6.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Penetration Testing', 'category' => 'Cybersecurity', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 79.99, 'duration_hours' => 28.0, 'difficulty_level' => 3.0],

            // Design
            ['course_name' => 'UI/UX Design Bootcamp', 'category' => 'Design', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 74.99, 'duration_hours' => 24.0, 'difficulty_level' => 1.5],
            ['course_name' => 'Figma UI Design Tutorial', 'category' => 'Design', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 5.0, 'difficulty_level' => 1.0],
            ['course_name' => 'Adobe XD Complete Guide', 'category' => 'Design', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 64.99, 'duration_hours' => 18.0, 'difficulty_level' => 1.5],
            ['course_name' => 'Graphic Design Masterclass', 'category' => 'Design', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 79.99, 'duration_hours' => 28.0, 'difficulty_level' => 1.5],
            ['course_name' => '3D Design with Blender', 'category' => 'Design', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 12.0, 'difficulty_level' => 2.0],

            // Game Development
            ['course_name' => 'Unity Game Development', 'category' => 'Game Development', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 84.99, 'duration_hours' => 42.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Unreal Engine 5 Complete Course', 'category' => 'Game Development', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 89.99, 'duration_hours' => 48.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Godot Game Engine Tutorial', 'category' => 'Game Development', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 8.0, 'difficulty_level' => 2.0],
            ['course_name' => 'C# for Unity Developers', 'category' => 'Game Development', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 69.99, 'duration_hours' => 22.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Game Design Fundamentals', 'category' => 'Game Development', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 15.0, 'difficulty_level' => 1.5],

            // Blockchain
            ['course_name' => 'Blockchain Basics', 'category' => 'Blockchain', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 12.0, 'difficulty_level' => 1.5],
            ['course_name' => 'Ethereum Smart Contracts', 'category' => 'Blockchain', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 79.99, 'duration_hours' => 24.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Solidity Programming', 'category' => 'Blockchain', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 6.0, 'difficulty_level' => 2.0],
            ['course_name' => 'NFT Development Course', 'category' => 'Blockchain', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 74.99, 'duration_hours' => 18.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Web3 Development', 'category' => 'Blockchain', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 10.0, 'difficulty_level' => 2.5],

            // Soft Skills & Communication
            ['course_name' => 'Public Speaking Mastery', 'category' => 'Soft Skills', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 64.99, 'duration_hours' => 12.0, 'difficulty_level' => 1.0],
            ['course_name' => 'Effective Communication', 'category' => 'Soft Skills', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 8.0, 'difficulty_level' => 1.0],
            ['course_name' => 'Productivity & Time Management', 'category' => 'Soft Skills', 'provider' => 'LinkedIn Learning', 'is_free' => false, 'cost' => 29.99, 'duration_hours' => 6.0, 'difficulty_level' => 1.0],
            ['course_name' => 'Emotional Intelligence', 'category' => 'Soft Skills', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 59.99, 'duration_hours' => 10.0, 'difficulty_level' => 1.5],
            ['course_name' => 'Critical Thinking Skills', 'category' => 'Soft Skills', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 4.0, 'difficulty_level' => 1.5],

            // More Business & Finance
            ['course_name' => 'Financial Accounting Fundamentals', 'category' => 'Business', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 16.0, 'difficulty_level' => 1.5],
            ['course_name' => 'Investment Banking', 'category' => 'Business', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 89.99, 'duration_hours' => 20.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Stock Market Investing', 'category' => 'Business', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 8.0, 'difficulty_level' => 1.5],
            ['course_name' => 'Excel Skills for Business', 'category' => 'Business', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 18.0, 'difficulty_level' => 1.0],
            ['course_name' => 'Business Strategy', 'category' => 'Business', 'provider' => 'Coursera', 'is_free' => false, 'cost' => 49.00, 'duration_hours' => 24.0, 'difficulty_level' => 2.0],

            // Additional Programming Languages
            ['course_name' => 'C++ Programming Masterclass', 'category' => 'Programming', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 79.99, 'duration_hours' => 32.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Java Programming Complete', 'category' => 'Programming', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 74.99, 'duration_hours' => 28.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Go Programming Language', 'category' => 'Programming', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 7.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Rust Programming Tutorial', 'category' => 'Programming', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 10.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Swift Programming Basics', 'category' => 'Programming', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 12.0, 'difficulty_level' => 1.5],

            // More Cloud & DevOps
            ['course_name' => 'Microsoft Azure Fundamentals', 'category' => 'Cloud Computing', 'provider' => 'Coursera', 'is_free' => true, 'duration_hours' => 16.0, 'difficulty_level' => 1.5],
            ['course_name' => 'Terraform Infrastructure as Code', 'category' => 'DevOps', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 74.99, 'duration_hours' => 18.0, 'difficulty_level' => 2.5],
            ['course_name' => 'Ansible Automation', 'category' => 'DevOps', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 5.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Jenkins CI/CD Pipeline', 'category' => 'DevOps', 'provider' => 'Udemy', 'is_free' => false, 'cost' => 59.99, 'duration_hours' => 14.0, 'difficulty_level' => 2.0],
            ['course_name' => 'Linux System Administration', 'category' => 'DevOps', 'provider' => 'YouTube', 'is_free' => true, 'duration_hours' => 8.0, 'difficulty_level' => 2.0],
        ];

        // Process additional courses
        foreach ($additionalCourses as $course) {
            $course['description'] = $course['description'] ?? 'Learn ' . $course['course_name'] . ' with practical examples and hands-on projects.';
            $course['url'] = $course['url'] ?? 'https://example.com/course/' . str_replace(' ', '-', strtolower($course['course_name']));
            $course['instructor'] = $course['instructor'] ?? 'Industry Expert';
            $course['related_skills'] = $course['related_skills'] ?? [$course['category'], 'Problem Solving'];
            $course['career_paths'] = $course['career_paths'] ?? ['Professional ' . $course['category']];
            $course['is_active'] = true;
            $courses[] = $course;
        }

        // Insert all courses
        foreach ($courses as $course) {
            Course::create($course);
        }

        $this->command->info('Successfully seeded ' . count($courses) . ' courses!');
    }
}
