<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class ChatController extends Controller
{
    private string $systemPrompt = <<<'PROMPT'
You are the AI assistant for PU Catalyst, a university career planning platform. You help students navigate the platform and provide career guidance. Be friendly, helpful, and give specific step-by-step instructions when asked about features.

## About PU Catalyst
PU Catalyst is an AI-powered platform that helps university students plan their career journey with personalized recommendations based on alumni success patterns. The platform has three user roles: Students, Alumni, and Admins.

## How to Register & Login
1. **Register**: Click "Get Started" on the landing page → Choose role (Student or Alumni) → Fill in name, email, password → Submit
2. **Login**: Click "Login" → Enter email and password → You'll be redirected to your dashboard
3. **Face Recognition Login**: After enabling 2FA in profile settings, you can login using facial recognition
4. **Forgot Password**: Click "Forgot password?" on login page → Enter email → Check email for reset link → Set new password
5. **Email Verification**: After registration, check your email for OTP code → Enter the code to verify your account

## Student Features

### Dashboard (/student/dashboard)
The main hub showing your progress, quick stats, AI recommendations, and recent activity. Key stats include:
- Roadmap Progress (completed skills)
- Total Skills tracked
- Certificates earned
- Organizations joined

### Career Roadmap (/student/roadmap)
This is the core feature! Here you can:
1. **Generate AI Roadmap**: Enter your dream job/career goal → AI creates a personalized semester-by-semester plan
2. **View Skills**: See required skills with status (Not Started, In Progress, Completed)
3. **Track Certificates**: Mark certificates as obtained
4. **Track Courses**: Monitor online courses progress
5. **Update Progress**: Click on any skill/certificate/course to update its status
6. **Save Roadmap**: Your progress is automatically saved

### How to Add Items to Roadmap:
- Skills, Certificates, Courses are generated by AI based on your career goal
- To regenerate: Click "Generate Roadmap" and enter a new career goal
- To update status: Click on any item → Select new status (Not Started/In Progress/Completed)

### Organization Explorer (/student/organizations)
Browse and discover student organizations:
- View organization descriptions and activities
- Filter by category
- See how organizations align with your career goals

### Certificate Explorer (/student/certificates)
Find recommended certifications:
- Browse available certifications
- See which are AI-recommended for your career path
- Click to view details and registration links

### Course Explorer (/student/courses)
Discover online courses:
- Browse courses from platforms like Coursera, Udemy, etc.
- See AI recommendations
- Track courses you're taking

### Profile Settings (/student/profile)
Manage your account:
- **Profile Tab**: Update name, email, bio, avatar
- **Security Tab**: Change password, Enable/Disable Face Recognition 2FA
- **Resume Tab**: Upload and manage your resume
- **Organizations Tab**: Add organizations you've joined
- **Certificates Tab**: Add certificates you've earned
- **Account Tab**: Delete account option

### How to Enable Face Recognition:
1. Go to Profile → Security Tab
2. Click "Enable Face Authentication"
3. Allow camera access
4. Position your face in the frame
5. Take 3 photos as instructed
6. Face auth is now enabled for login and verification

## Alumni Features
Alumni can share their career journey to help train the AI:
- Complete career profile with job history
- Share which skills, certifications, and organizations helped their career
- Mentor current students (coming soon)

## Common Questions

Q: How do I start planning my career?
A: Go to the Roadmap page (/student/roadmap) and enter your dream job. The AI will create a personalized plan.

Q: How do I add a certificate I earned?
A: Go to Profile → Certificates Tab → Click "Add Certificate" → Fill in the details

Q: How do I track my progress?
A: Your Dashboard shows overall progress. For detailed tracking, visit the Roadmap page and update skill statuses.

Q: How does the AI recommendation work?
A: Our AI analyzes alumni career data to find patterns. It recommends skills, courses, and certificates that successful alumni in your target career had.

Q: Can I change my career goal?
A: Yes! Go to Roadmap → Generate a new roadmap with a different career goal. You can have multiple roadmaps.

Q: Is my data private?
A: Yes, your personal data is secure. Alumni data used for AI is anonymized.

Always be encouraging and helpful. If you don't know something specific about the platform, suggest they explore the relevant section or contact support.
PROMPT;


    /**
     * Send a message to AI and get a response
     */
    public function sendMessage(Request $request)
    {
        $request->validate([
            'message' => 'required|string|max:4000',
            'history' => 'array',
            'model' => 'string|nullable',
        ]);

        $selectedModel = $request->input('model', 'auto');

        // If auto, try providers in order
        if ($selectedModel === 'auto') {
            return $this->autoSelectModel($request);
        }

        // Determine provider from model name
        if (str_starts_with($selectedModel, 'gemini-')) {
            return $this->callGemini($selectedModel, $request);
        } elseif (str_starts_with($selectedModel, 'llama-')) {
            return $this->callGroq($selectedModel, $request);
        }

        return response()->json(['error' => 'Invalid model selected'], 400);
    }

    /**
     * Auto-select model with fallback chain
     */
    private function autoSelectModel(Request $request)
    {
        // Try Gemini first
        $geminiKey = config('services.gemini.api_key');
        if ($geminiKey) {
            $models = ['gemini-2.0-flash-001', 'gemini-2.0-flash-exp', 'gemini-1.5-flash-8b'];
            foreach ($models as $model) {
                $result = $this->tryGeminiModel($model, $geminiKey, $request);
                if ($result['success']) {
                    return response()->json([
                        'response' => $result['text'],
                        'model' => $model
                    ]);
                }
            }
        }

        // Fallback to Groq
        $groqKey = config('services.groq.api_key');
        if ($groqKey) {
            $result = $this->tryGroqModel('llama-3.1-8b-instant', $groqKey, $request);
            if ($result['success']) {
                return response()->json([
                    'response' => $result['text'],
                    'model' => 'llama-3.1-8b-instant'
                ]);
            }
        }

        return response()->json([
            'error' => 'AI service is temporarily unavailable. Please try again in a moment.'
        ], 503);
    }

    /**
     * Call Gemini with specific model
     */
    private function callGemini(string $model, Request $request)
    {
        $apiKey = config('services.gemini.api_key');
        if (!$apiKey) {
            return response()->json(['error' => 'Gemini API key not configured'], 500);
        }

        $result = $this->tryGeminiModel($model, $apiKey, $request);
        if ($result['success']) {
            return response()->json([
                'response' => $result['text'],
                'model' => $model
            ]);
        }

        return response()->json(['error' => $result['error'] ?? 'Failed to get response'], 500);
    }

    /**
     * Call Groq with specific model
     */
    private function callGroq(string $model, Request $request)
    {
        $apiKey = config('services.groq.api_key');
        if (!$apiKey) {
            return response()->json(['error' => 'Groq API key not configured'], 500);
        }

        $result = $this->tryGroqModel($model, $apiKey, $request);
        if ($result['success']) {
            return response()->json([
                'response' => $result['text'],
                'model' => $model
            ]);
        }

        return response()->json(['error' => $result['error'] ?? 'Failed to get response'], 500);
    }

    /**
     * Try a specific Gemini model
     */
    private function tryGeminiModel(string $model, string $apiKey, Request $request): array
    {
        try {
            $contents = $this->buildGeminiContents($request);

            $response = Http::timeout(30)->post(
                "https://generativelanguage.googleapis.com/v1beta/models/{$model}:generateContent?key={$apiKey}",
                [
                    'contents' => $contents,
                    'generationConfig' => [
                        'temperature' => 0.7,
                        'topK' => 40,
                        'topP' => 0.95,
                        'maxOutputTokens' => 1024,
                    ],
                ]
            );

            if ($response->successful()) {
                $data = $response->json();
                $text = $data['candidates'][0]['content']['parts'][0]['text'] ?? null;
                if ($text) {
                    return ['success' => true, 'text' => $text];
                }
            }

            $body = $response->body();
            $isRateLimited = $response->status() === 429 ||
                $response->status() === 404 ||
                str_contains($body, 'RESOURCE_EXHAUSTED') ||
                str_contains($body, 'quota');

            Log::error("Gemini error on {$model}", ['status' => $response->status(), 'body' => substr($body, 0, 300)]);

            return [
                'success' => false,
                'error' => $isRateLimited ? 'Rate limit exceeded. Try another model.' : 'Failed to get response',
                'rateLimited' => $isRateLimited
            ];
        } catch (\Exception $e) {
            Log::error("Gemini exception on {$model}", ['msg' => $e->getMessage()]);
            return ['success' => false, 'error' => 'Connection error'];
        }
    }

    /**
     * Try a specific Groq model
     */
    private function tryGroqModel(string $model, string $apiKey, Request $request): array
    {
        try {
            $messages = $this->buildGroqMessages($request);

            $response = Http::timeout(30)
                ->withHeaders([
                    'Authorization' => "Bearer {$apiKey}",
                    'Content-Type' => 'application/json',
                ])
                ->post('https://api.groq.com/openai/v1/chat/completions', [
                    'model' => $model,
                    'messages' => $messages,
                    'temperature' => 0.7,
                    'max_tokens' => 1024,
                ]);

            if ($response->successful()) {
                $data = $response->json();
                $text = $data['choices'][0]['message']['content'] ?? null;
                if ($text) {
                    return ['success' => true, 'text' => $text];
                }
            }

            Log::error('Groq API error', [
                'model' => $model,
                'status' => $response->status(),
                'body' => substr($response->body(), 0, 300)
            ]);

            return ['success' => false, 'error' => 'Failed to get response from Groq'];
        } catch (\Exception $e) {
            Log::error('Groq exception', ['msg' => $e->getMessage()]);
            return ['success' => false, 'error' => 'Connection error'];
        }
    }

    /**
     * Build contents array for Gemini API
     */
    private function buildGeminiContents(Request $request): array
    {
        $contents = [];

        if ($request->has('history') && is_array($request->history)) {
            foreach ($request->history as $msg) {
                $contents[] = [
                    'role' => $msg['role'] === 'user' ? 'user' : 'model',
                    'parts' => [['text' => $msg['content']]]
                ];
            }
        }

        $contents[] = [
            'role' => 'user',
            'parts' => [['text' => $request->message]]
        ];

        // Prepend system context to first message
        if (count($contents) === 1) {
            $contents[0]['parts'][0]['text'] = $this->systemPrompt . "\n\nUser: " . $request->message;
        }

        return $contents;
    }

    /**
     * Build messages array for Groq API (OpenAI format)
     */
    private function buildGroqMessages(Request $request): array
    {
        $messages = [
            ['role' => 'system', 'content' => $this->systemPrompt]
        ];

        if ($request->has('history') && is_array($request->history)) {
            foreach ($request->history as $msg) {
                $messages[] = [
                    'role' => $msg['role'] === 'user' ? 'user' : 'assistant',
                    'content' => $msg['content']
                ];
            }
        }

        $messages[] = [
            'role' => 'user',
            'content' => $request->message
        ];

        return $messages;
    }
}
